### List Customers

GET http://localhost:3000/customers

### Get Developer

GET http://localhost:3000/customers/1

### Create Developer

POST http://localhost:3000/customers
Content-Type: application/json

{
  "fullName": "Maria",
  "birthDate": "",
  "cpf": "12345678900",
  "cep": "25250010",
  "address": "Rua Maia de Lacerda",
  "complementAddress": "91 apt 207",
  "phoneNumbers": [],
  "email":"marialuiza@mail.com",
  "creditHistory": [],
  "accounts": [],
  "managerId": 1
}

### Update Developer

PATCH http://localhost:3000/customers/1
Content-Type: application/json

{
    "cep": "25250001"
}


### Delete Developer

DELETE http://localhost:3000/developers/1
