### List Accounts

GET http://localhost:3000/accounts

### Get Account

GET http://localhost:3000/accounts/1

### Create Account

POST http://localhost:3000/accounts
Content-Type: application/json

{
    "accountNumber": "123",
    "balance": 123,
    "transactions": []
}

### Update Account

PATCH http://localhost:3000/accounts/1
Content-Type: application/json

{
    "balance":1234
}


### Delete Account

DELETE http://localhost:3000/accounts/1
