### List Developers

GET http://localhost:3000/developers

### Get Developer

GET http://localhost:3000/developers/dev_oiblhsVd0OMRyTyHz6dof

### Create Developer

POST http://localhost:3000/developers
Content-Type: application/json

{
    "name":"Luiza",
    "email":"maria.mourao@gmail.com",
    "dateOfBirth": "1997-03-07"
}

### Update Developer

PATCH http://localhost:3000/developers/dev_oiblhsVd0OMRyTyHz6dof
Content-Type: application/json

{
    "name":"Matheus"
}


### Delete Developer

DELETE http://localhost:3000/developers/dev_oiblhsVd0OMRyTyHz6dof
