### List Savings Accounts

GET http://localhost:3000/savings_accounts

### Get Developer

GET http://localhost:3000/savings_accounts/1

### Create Developer

POST http://localhost:3000/savings_accounts
Content-Type: application/json

{

  "accountId": 123,
  "interestRate": 123,
  "yieldAmount": 123
}

### Update Developer

PATCH http://localhost:3000/savings_accounts/1
Content-Type: application/json

{
    "accountId": 1234
}


### Delete Developer

DELETE http://localhost:3000/savings_accounts/1
